sudo: required
dist: trusty

language: cpp

env:
  - C_COMPILER=gcc-5 CXX_COMPILER=g++-5

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-5 g++-5 -y
  - sudo apt-get install libboost-all-dev libeigen3-dev libopencv-dev -y

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DBUILD_EXAMPLES=on -DBUILD_UTILS=on ..

script:
  - make VERBOSE=1
