dist: trusty # Use 'trusty' unless specified otherwise
os: linux # Use Linux unless specified otherwise
sudo: false

language: cpp

matrix:
  include:
    - env: C_COMPILER=gcc-7 CXX_COMPILER=g++-7
      addons: { apt: { packages: ["g++-7"], sources: ["ubuntu-toolchain-r-test"] } }

    - env: C_COMPILER=clang-5.0 CXX_COMPILER=clang++-5.0
      addons: { apt: { packages: ["clang-5.0"], sources: ["llvm-toolchain-trusty-5.0", "ubuntu-toolchain-r-test"] } }

    - os: osx
      env: C_COMPILER=clang CXX_COMPILER=clang++
      osx_image: xcode9.2

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pyenv global system 3.6; fi # Workaround for travis-ci/issues/8363
  - sudo apt-get update -q
  - sudo apt-get install libboost-all-dev libopencv-dev -y
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      wget https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz
      tar -xvzf cmake-3.8.2-Linux-x86_64.tar.gz
    else
      brew install cmake || brew upgrade cmake
    fi

before_script:
  - mkdir build
  - cd build
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      ../cmake-3.8.2-Linux-x86_64/bin/cmake -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DEOS_BUILD_EXAMPLES=on -DEOS_BUILD_UTILS=on -DEOS_GENERATE_PYTHON_BINDINGS=on -DPYTHON_EXECUTABLE=`which python3.6` ..
    else
      cmake -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DEOS_BUILD_EXAMPLES=on -DEOS_BUILD_UTILS=on -DEOS_GENERATE_PYTHON_BINDINGS=on -DPYTHON_EXECUTABLE=`which python3.6` ..
    fi

script:
  - make VERBOSE=1
